/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for participant.json — off-chain metadata for Flare ecosystem participants registered via the ParticipantRegister contract.
 */
export interface FlareParticipantMetadata {
  /**
   * JSON-LD context. Must include Schema.org vocab and flare namespace.
   */
  "@context": {
    [k: string]: unknown;
  };
  "@type": "Organization";
  /**
   * Display name of the participant.
   */
  name: string;
  /**
   * Short description of the participant and their services.
   */
  description?: string;
  /**
   * Website URL.
   */
  url: string;
  /**
   * Direct URL to the primary logo image. Universal fallback — consumers use this when no theme-specific or square variant is available.
   */
  logo?: string;
  /**
   * Theme-aware and shape-specific logo variants. All optional. Consumers fall back to top-level `logo` if absent.
   */
  "flare:brand"?: {
    /**
     * Logo variant for light backgrounds (dark mark/text on transparent).
     */
    light?: string;
    /**
     * Logo variant for dark backgrounds (light mark/text on transparent).
     */
    dark?: string;
    /**
     * Square mark / icon (recommended 512x512, symbol only). Used for avatars, directory tiles, favicons.
     */
    icon?: string;
  };
  /**
   * Social media usernames (not full URLs).
   */
  "flare:social"?: {
    twitter?: string;
    telegram?: string;
    discord?: string;
    github?: string;
  };
  /**
   * Organization domicile.
   */
  "flare:location"?: {
    /**
     * ISO 3166-1 alpha-2 country code.
     */
    country?: string;
  };
  /**
   * Services the participant operates.
   */
  "flare:services"?: (
    | "ftso"
    | "fdc"
    | "fast-updates"
    | "validator"
    | "fassets-agent"
    | "lending"
    | "dex"
    | "staking"
  )[];
  /**
   * Infrastructure node declarations. Declares where nodes run physically.
   */
  "flare:nodes"?: {
    network: "flare" | "songbird" | "coston2" | "coston";
    role: "validator" | "observer" | "fdc-verifier" | "rpc" | "indexer";
    /**
     * ISO 3166-1 alpha-2 country code where the node physically runs.
     */
    country: string;
  }[];
  /**
   * Public RPC endpoints offered by this participant.
   */
  "flare:rpc"?: {
    network: "flare" | "songbird" | "coston2" | "coston";
    url: string;
  }[];
  [k: string]: unknown;
}
