/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for participant.json — off-chain metadata for Flare ecosystem participants registered via the ParticipantRegister contract. Current canonical structure uses `flare:networks` for per-chain service breakdown; the flat `flare:services` array is retained for backward compatibility but deprecated. Infrastructure is split into two arrays: `flare:nodes` for operational hardware (where the participant physically runs nodes — implicitly internal), and `flare:tools` for public ecosystem services the participant publishes for the community (RPCs, dashboards, explorers, faucets, etc.). The legacy `flare:rpc` array is retained for backward compatibility but deprecated.
 */
export interface FlareParticipantMetadata {
  /**
   * JSON-LD context. Must include Schema.org vocab and flare namespace.
   */
  "@context": {
    [k: string]: unknown;
  };
  "@type": "Organization";
  /**
   * Display name of the participant.
   */
  name: string;
  /**
   * Short description of the participant and their services.
   */
  description?: string;
  /**
   * Website URL.
   */
  url: string;
  /**
   * Direct URL to the primary logo image. Universal fallback — consumers use this when no theme-specific or square variant is available.
   */
  logo?: string;
  /**
   * Theme-aware and shape-specific logo variants. All optional. Consumers fall back to top-level `logo` if absent.
   */
  "flare:brand"?: {
    /**
     * Logo variant for light backgrounds (dark mark/text on transparent).
     */
    light?: string;
    /**
     * Logo variant for dark backgrounds (light mark/text on transparent).
     */
    dark?: string;
    /**
     * Square mark / icon (recommended 512x512, symbol only). Used for avatars, directory tiles, favicons.
     */
    icon?: string;
  };
  /**
   * Social media usernames (not full URLs).
   */
  "flare:social"?: {
    twitter?: string;
    telegram?: string;
    discord?: string;
    github?: string;
  };
  /**
   * Organization domicile.
   */
  "flare:location"?: {
    /**
     * ISO 3166-1 alpha-2 country code.
     */
    country?: string;
  };
  /**
   * DEPRECATED — use `flare:networks` for per-chain service breakdown. This flat list is retained for backward compatibility with pre-2026-05-09 participant.json files. New JSONs should use `flare:networks` instead.
   */
  "flare:services"?: (
    | "ftso"
    | "fdc"
    | "fast-updates"
    | "validator"
    | "fassets-agent"
    | "lending"
    | "dex"
    | "staking"
  )[];
  /**
   * Networks the participant operates on, with per-network service breakdown. Current canonical structure (supersedes the flat `flare:services` array). Each entry pairs a chain id with the services the participant offers on that chain.
   */
  "flare:networks"?: {
    /**
     * Chain identifier the entry applies to.
     */
    id: "flare" | "songbird" | "coston2" | "coston";
    services: ("ftso" | "fdc" | "fast-updates" | "validator" | "fassets-agent" | "lending" | "dex" | "staking")[];
  }[];
  /**
   * Numeric ParticipantType enum value the wallet registered under, mirroring the on-chain (participantType, infoURI) tuple. MUST equal the value used in register(). Lets JSON consumers verify the document matches the on-chain registration without an additional RPC call. Enum: 0=Provider, 1=DeFi, 2=Wallet, 3=Tool, 4=FAssetsAgent, 5=Exchange, 6=App, 7=AgenticAI.
   */
  "flare:participant-type"?: number;
  /**
   * Human-readable mirror of flare:participant-type for indexers and UIs that prefer string keys. MUST match the numeric value (Provider↔0, DeFi↔1, Wallet↔2, Tool↔3, FAssets Agent↔4, Exchange↔5, App↔6, Agentic AI↔7).
   */
  "flare:participant-type-label"?:
    | "Provider"
    | "DeFi"
    | "Wallet"
    | "Tool"
    | "FAssets Agent"
    | "Exchange"
    | "App"
    | "Agentic AI";
  /**
   * Infrastructure node declarations. Declares where nodes run physically.
   */
  "flare:nodes"?: {
    network: "flare" | "songbird" | "coston2" | "coston";
    role: "validator" | "observer" | "fdc-verifier" | "rpc" | "indexer";
    /**
     * ISO 3166-1 alpha-2 country code where the node physically runs.
     */
    country: string;
  }[];
  /**
   * Public ecosystem services the participant publishes for the community. Always public, always has a URL. Distinct from `flare:nodes` which declares operational hardware. Use for RPCs, block explorers, dashboards, indexers, faucets, bridges, subgraphs, analytics surfaces, dev tooling, educational sites — anything an external user can browse to or call.
   */
  "flare:tools"?: {
    /**
     * Display name of the tool (e.g. "AU.CC Flare RPC", "Flare Builders").
     */
    name: string;
    /**
     * Public URL where the tool is reachable. MUST be https://.
     */
    url: string;
    /**
     * Kind of public service. `rpc` = JSON-RPC endpoint; `explorer` = block explorer; `indexer` = indexer/API over chain data; `archive` = archive-node endpoint; `dashboard` = web dashboard/observability surface; `faucet` = testnet faucet; `bridge` = cross-chain bridge UI; `subgraph` = hosted subgraph endpoint; `analytics` = analytics/metrics surface; `dev-tool` = developer tooling (SDK docs, deployer UI, etc.); `educational` = educational/docs site; `other` = catch-all.
     */
    category:
      | "rpc"
      | "explorer"
      | "indexer"
      | "archive"
      | "dashboard"
      | "faucet"
      | "bridge"
      | "subgraph"
      | "analytics"
      | "dev-tool"
      | "educational"
      | "other";
    /**
     * Chains the tool serves. Omit when the tool is chain-agnostic (e.g. an educational site).
     */
    networks?: ("flare" | "songbird" | "coston2" | "coston")[];
    /**
     * Optional one-line description of the tool.
     */
    description?: string;
  }[];
  /**
   * DEPRECATED — use `flare:tools` with `category: "rpc"` for public RPC endpoints. This array is retained for backward compatibility with pre-2026-05-13 participant.json files. New JSONs should use `flare:tools` instead.
   */
  "flare:rpc"?: {
    network: "flare" | "songbird" | "coston2" | "coston";
    url: string;
  }[];
  [k: string]: unknown;
}
